feat: add file upload
tempfiles-Team/tempfiles-frontend-v2 pull request #14
Opened 2023-08-03 10:24 UTC by choi138

## 🔍 What is this PR?
**이 PR은 어떤 것이 변화했나요? 설명해주세요**
- 이슈 넘버: #13 

## 📸 스크린 샷
**어떤 점이 달라졌는지 알 수 있게끔 스크린 샷을 첨부해주세요.**
<img width="911" alt="Screenshot 2023-08-03 at 7 24 33 PM" src="https://github.com/tempfiles-Team/tempfiles-frontend-v2/assets/84369321/3297c387-b3ac-4850-a4fe-8c0a70f343f0">

## ✅ 체크 리스트
- [ ]  **테스트 계획 또는 완료된 사항의 체크리스트를 작성해주세요.**

2023-08-04 01:47 UTC, ananjaemin requested changes

2023-08-04 01:47 UTC, ananjaemin commented on src/pages/main/index.tsx
> +  };
이런건 따로 utils파일 같은 곳에 분류 해두면 좋을 것 같아.

2023-08-04 01:47 UTC, ananjaemin commented on src/pages/main/index.tsx
> +  const { handleSubmit } = useForm();
useForm을 사용한 이유가 있을까? 지금 코드만 보면 그냥 onClick만 사용해도 되는데 handleSubmit을 사용했어서

2023-08-04 01:47 UTC, ananjaemin commented on src/pages/main/index.tsx
>    const [activeOption, setActiveOption] = useState(UPLOAD_OPTIONS_LIST.map(() => false));
이건 자기 맘이긴한데
난 솔직히 여기서 activeOption[0], activeOption[1],... 이런식으로 가져오는거 맘에 안들기도하고 다른 사람이 코드를 보기에 어렵기도해 activeOption['유지기간'] 이런식으로 가져오면 좋을것같아 ㅎ 물론 자동완성도 되게 타입 최적화도 해야하고 화이팅!

2023-08-04 01:47 UTC, ananjaemin commented on src/pages/main/index.tsx
>    const [activeOption, setActiveOption] = useState(UPLOAD_OPTIONS_LIST.map(() => false));
```
export type UPLOAD_OPTIONS_LIST_TYPE = '유지기간' | '다운로드 횟수' | '비밀번호';

export const UPLOAD_OPTIONS_LIST: UPLOAD_OPTIONS_LIST_TYPE[] = [
  '유지기간',
  '다운로드 횟수',
  '비밀번호',
];

```
```
  type ActiveOptionState = { [key in UPLOAD_OPTIONS_LIST_TYPE]?: boolean };
  const [activeOption2, setActiveOption2] = useState<ActiveOptionState>(() => {
    const initialState: ActiveOptionState = {};
    UPLOAD_OPTIONS_LIST.forEach((option) => {
      initialState[option] = false;
    });
    return initialState;
  });
```
  난 이런식으로 해봤는데 더 좋은 방법이 있나 생각해줘

2023-08-04 01:47 UTC, ananjaemin commented on src/api/file.ts
> +};
내가 졸려서 헷갈리는 건가 위에서 instance 잘 만들어 놨는데 사용을 안하넹..

2023-08-04 01:48 UTC, minpeter requested changes

2023-08-04 01:48 UTC, minpeter commented on .env.sample
이게 백엔드 URL 환경변수인가요?
이 상태로 main 브랜치가면 업로드 안되겠는데요..? 인프라 코드에 환경변수 추가해둘까요?

2023-08-04 01:52 UTC, choi138 commented on src/api/file.ts
> +};
위에 만든 instance는 header가 없을때 사용하려고 만들었어요.
근데 파일 업로드 할 때는 header가 있어서 따로 만들었습니다

2023-08-04 01:52 UTC, choi138 commented on .env.sample
백엔드 URL 환경 변수 맞아요!

2023-08-04 01:55 UTC, choi138 commented on src/pages/main/index.tsx
> +  const { handleSubmit } = useForm();
생각해보니 굳이 사용할 필요가 없을것 같아요
수정하겠습니다!

2023-08-04 01:58 UTC, ananjaemin commented on src/api/file.ts
> +};
```
  const { data } = await instance.post(
    `${API_SUFFIX.UPLOAD}${password ? `?pw=${password}` : ''}`,
    file,
    {
      headers: {
        'Content-Type': 'multipart/form-data',
        'X-Download-Limit': downloadLimit,
        'X-Time-Limit': timeLimit,
      },
    },
  );
```
이런식으로 header도 따로 넣을 수 있긴해

2023-08-04 06:30 UTC, minpeter commented on .env.sample
인프라 수정해보고 말씀드릴게요 :)

2023-08-04 06:38 UTC, minpeter commented on .env.sample
![image](https://github.com/tempfiles-Team/tempfiles-frontend-v2/assets/62207008/cd7070a7-4941-4fc0-a2a4-46716b1b6a2e)
이건 좀 수정을 하셔야겠는데요..? 왜이럴까요?

2023-08-05 05:46 UTC, choi138 commented on src/pages/main/index.tsx
>    const [activeOption, setActiveOption] = useState(UPLOAD_OPTIONS_LIST.map(() => false));
너무 좋은 방법인것 같습니다!

2023-08-05 05:47 UTC, choi138 commented on src/api/file.ts
> +};
오,,, 이건 몰랐네요.. 바로 적용하겠습니다!

2023-08-05 10:00 UTC, ananjaemin approved these changes

2023-08-05 10:13 UTC, merged