feat: add text upload
tempfiles-Team/tempfiles-frontend-v2 pull request #18
Opened 2023-08-09 11:28 UTC by choi138

## 🔍 What is this PR?
**이 PR은 어떤 것이 변화했나요? 설명해주세요**
- 이슈 넘버: #17 

## 📸 스크린 샷
**어떤 점이 달라졌는지 알 수 있게끔 스크린 샷을 첨부해주세요.**
<img width="975" alt="Screenshot 2023-08-09 at 8 27 51 PM" src="https://github.com/tempfiles-Team/tempfiles-frontend-v2/assets/84369321/9b5e18c2-8b50-4591-a95b-157d678c63f2">

## ✅ 체크 리스트
- [ ]  **테스트 계획 또는 완료된 사항의 체크리스트를 작성해주세요.**

2023-08-09 12:24 UTC, ananjaemin requested changes

2023-08-09 12:24 UTC, ananjaemin commented on package.json
> +    "@mui/material": "^5.14.4",
빼애에에엑!

2023-08-09 12:24 UTC, ananjaemin commented on src/api/text.ts
> +  instance.defaults.headers['X-Time-Limit'] = timeLimit;
file은 
```
  const { data } = await instance.post(
    `${API_SUFFIX.UPLOAD}${password ? `?pw=${password}` : ''}`,
    file,
    {
      headers: {
        'Content-Type': 'multipart/form-data',
        'X-Download-Limit': downloadLimit,
        'X-Time-Limit': timeLimit,
      },
    },
  );
```
이렇게 했는데 여기는 왜 이렇게 헀죠 -> 통일이 필요
그리고 저렇게 하면 다른 api사용할때도 헤더에 저게 들어가게되서
불필요한 헤더가 추가된다.
(물론 여기서는 성능상이나 보안상이나 문제는 없지만)

2023-08-09 12:24 UTC, ananjaemin commented on src/components/common/Navbar/index.tsx
> +        </S.NavbarText>
알고있을것같지만 key에는 index 넣지 맙시다
여기서는 상관없긴해도 eslint 빡세게 잡는곳은 이런거 다 제한해둔다

2023-08-09 12:24 UTC, ananjaemin commented on src/hooks/query/text/useUploadText.ts
> +      //   navigation(`/text/${id}`);
메인에 PR할때는 이런 코드는 없애주는게 좋다. (주석,test코드,등등)
다른곳도 마찬가지.

2023-08-09 12:24 UTC, ananjaemin commented on src/hooks/query/text/useUploadText.ts
> +      //   navigation(`/text/${id}`);
물론 다른 사람이 보기 좋게 설명하는 그런 주석말고~

2023-08-09 12:24 UTC, ananjaemin commented on src/pages/main/index.tsx
> +    }
음...이건 너가 봐도 조금 그렇지..?
나라면 custom hook만들어서 formData, text 유무만으로 판별해서 Mutate했을것같아
차피 나머지 옵션은 똑같으니까 그대로 넣어주고

2023-08-09 12:24 UTC, ananjaemin commented on src/pages/main/index.tsx
> +    }
`const {tilmeLimit,downloadLimit,password} = options` 이렇게하면 
`timeLimit: options.timeLimit` 이런식으로 안하고 `timeLimit` 이렇게도 넘겨줄수있지

2023-08-09 12:24 UTC, ananjaemin commented on src/pages/main/index.tsx
> +
MainPageTextArea부분에 text를 value란 prop에 넘겨주면 더 간단해진다.

2023-08-09 12:24 UTC, ananjaemin commented on src/pages/main/index.tsx
>            {!textClick ? (
삼항연산자는 되도록 2중으로 안쓰는게 좋다.

2023-08-09 12:33 UTC, ananjaemin commented
내 말이 정답은 아니니 자신이 생각했을때 어떤게 좋다고 생각하면 언제든지 편히 말해주세용

2023-08-10 00:56 UTC, choi138 commented on src/api/text.ts
> +  instance.defaults.headers['X-Time-Limit'] = timeLimit;
{}로 보내면 백엔드에서 데이터로 인식하기 때문에 textData 에 저 헤더 문구가 그대로 들어가게 되어서 저렇게 했습니다.

2023-08-10 09:21 UTC, choi138 commented on src/components/common/Navbar/index.tsx
> +        </S.NavbarText>
href값으로 바꿨습니다!

2023-08-10 10:27 UTC, ananjaemin commented on src/api/text.ts
> +        'Content-Type': 'multipart/form-data',
이것도 폼데이터인가?

2023-08-10 10:28 UTC, choi138 commented on src/api/text.ts
> +        'Content-Type': 'multipart/form-data',
어후 실수 했네요 수정하겠습니다

2023-08-10 10:33 UTC, ananjaemin commented on src/pages/main/index.tsx
> +    }
+ `{ file : formData , ...option }` 도 가능

2023-08-10 10:38 UTC, choi138 commented
코드 리팩토링 완료 했습니다! 더 수정할거 있으면 말씀해주세요

2023-08-14 12:29 UTC, ananjaemin approved these changes

2023-08-15 07:14 UTC, merged